### ISSUE TITLE
Comparison and Benchmark against CWPack

### ISSUE THREAD

**Issue by roniemartinez** [ludocode/mpack#51] opened 2017-03-14 09:38 UTC
Hi,

It seems that a new competitor, [CWPack](https://github.com/clwi/CWPack), is claiming to be faster than MPack. Hoping for updated comparison and benchmark.

Cheers!

**Comment by ludocode** [comment] 2017-03-15 03:08
Nice! Thanks for the heads up. It looks interesting. I was able to run his benchmark and reproduce his results. Some quick notes:

- It seems marginally faster on most write operations. I haven't looked into why that is yet. Nothing springs to mind. In theory they should be almost identical.

- It seems faster in all of the dynamic reads, but that may just be because the benchmark doesn't actually use the result. (`cw_unpack_next()` places the result in the context. MPack and CMP return it, so they are disadvantaged by moving the result up the stack, but that may actually be an advantage if the data was actually used.) Adding it to my benchmark suite may shed some light here.

- It seems much faster on `mpack_write_str()` which is critical and kind of scary. There's at least one problem here which is that MPack does a space check twice: once to write the tag, and again to write the string. There may be more problems if there is this large of a speed difference. There's definitely an optimization needed here.

- It's somewhat faster at discarding a string. Maybe an `mpack_expect_str_inplace()` function is needed here, or something that can read a tag plus pointer from a buffer that is assumed contiguous. I think CMP and CWPack both assume a contiguous read buffer here which makes things a whole lot easier, but MPack should be able to get the same speed if the buffer actually is contiguous.

So maybe it is faster! At least in this specific case of encoding/decoding from a huge pre-allocated buffer. I'll have to add it to my benchmarks and see how it performs. I do want to focus on finishing MPack 0.9 first though. I've clearly done very little work on it lately, so this may be the motivation I need to get working again.

**Comment by roniemartinez** [comment] 2017-03-15 03:54
Cool!

We will be waiting for the new version and also the benchmark results. 👍

**Comment by clwi** [comment] 2017-03-28 14:38
Nice speed increase in the develop branch. I think it's time for me to change the README for CWPack.

**Comment by ludocode** [comment] 2017-03-30 03:30
Thanks 👍 I've added a branch with CWPack support to the schemaless benchmarks:

https://github.com/ludocode/schemaless-benchmarks/commit/e062f543596271be3e3d85a8a613e396f5c440ec

It's a bit complicated to run against the MPack develop branch. Probably you'll want to amalgamate MPack develop and replace the one it uses, and then modify the Makefile point CWPack to your local copy for development purposes.

I'm a bit far away from a release for MPack right now unfortunately. I need to finish and merge the tree-stream branch at some point (I've got a bunch of work locally that I haven't pushed yet, and still quite a bit more work to get it all working and properly unit tested.)

Once that's released I'll update all the libraries in the schemaless benchmarks. MongoDB had a huge release around the same time as I first posted the benchmarks so I want to see if they've caught up to MPack and libbson. The reference msgpack-c implementation has also had some very big releases in the past year so we'll see if they've improved

**Comment by ludocode** [comment] 2019-09-22 05:31
I haven't really had time to revisit the benchmarks and probably won't any time soon. I'm adding some new features to MPack that may slightly slow it down as well. @clwi It's probably safe to say that CWPack is faster than MPack again and will be for the foreseeable future so you can remove the exception from your README. I'm going to close this for now since it will be a while before I get back to micro-optimizing MPack.

**Closed as completed by ludocode** 2019-09-22 05:31 UTC
