### ISSUE TITLE
MPACK_HAS_GENERIC autodetection is bugged with clang and/or C++ compiler

### ISSUE THREAD

**Issue by xor-gate** [ludocode/mpack#42] opened 2016-04-11 11:50 UTC
With clang 3.7 the generic autodetection is bugged. Because of the following issue:
See http://clang-developers.42468.n3.nabble.com/Generic-compiles-fine-in-c-source-td4037233.html

**Comment by ludocode** [comment] 2016-04-11 23:31
Do you mean that it detects `_Generic` support even in C++? This was intended when I changed how it detects `MPACK_HAS_GENERIC`. Clang supports `_Generic` as an extension in both C and C++ regardless of language version, so I figured we could use it even in C++ since this way it's closer to the C code.

I think the behavior I intended was a mistake though, and we should be using the C++ overloads in C++ mode even if the compiler supports `_Generic`. I'll be adding C++ bindings at some point in the near future (possibly before 0.9), and I'll want some additional overloads specifically for C++. For example we'll want to support `mpack_write()` for `std::string`, `std::vector<char>`, and more.

What I'll most likely do is keep the detection of `MPACK_HAS_GENERIC` the way it is (since it is correctly detecting that Clang does actually support `_Generic`), but the type-generic `mpack_write()` macro will only be available in C mode, not C++. This way it will use the overloads in C++.

**Comment by ludocode** [comment] 2016-04-11 23:34
Something else I forgot to mention: I fixed the weird behavior you mentioned in https://github.com/ludocode/mpack/pull/36#discussion_r53977282 where `mpack_write()` wouldn't accept a string literal in Clang. This was fixed in 91a3ffa300fb61473b218eefb46843d0e28e778f: using the array in a comma operator causes Clang to decay it to a pointer (whereas GCC does it automatically when an array is used as an argument to a `_Generic`.) This fix is included in 0.8.2.

**Closed** 2016-04-12 01:37 UTC

**Comment by xor-gate** [comment] 2016-04-12 06:56
Good point about the decaying of the array operator. I was wondering what the fixed did :-). Yeah I exactly mean enabling _Generic in C++ when the compiler says it supports it was not a good idea. When I started to create this issue I had some other problems with the _Generic const vs non-const selector, but this was due to a difference in gcc, clang 3.7 and clang 3.8. Thanks for mentioning and improving the autodetection of the _Generic before other people will have problems :-).

**Comment by ludocode** [comment] 2016-04-12 12:27
Note that if you update to the latest develop version (0.9dev), the config file is now optional and disabled by default. You have to define `MPACK_HAS_CONFIG` to use it. This is one of a few breaking changes that are going into 0.9 (I'm trying to get all breaking changes in the same release to prepare for 1.0.)

**Comment by xor-gate** [comment] 2016-04-12 12:31
Thanks for the notice, hopefully you did document this for other people :-).

**Comment by ludocode** [comment] 2016-04-12 12:34
I was planning on putting it in the release notes, but you're right, I should probably maintain a CHANGELOG with this stuff in it so people can see what they're getting if they use development versions.

**Comment by xor-gate** [comment] 2016-04-12 12:37
I think CHANGELOG should be updated accordingly as development proceeds. Then when a release is bumped the part which is relevant for the release should be copied to the github release page. Because when people have a amalgamated package floating around on disk they can always open the local CHANGELOG :+1:
