### ISSUE TITLE
Undefined configuration and compiler definitions cause warnings

### ISSUE THREAD

**Issue by rikvdh** [ludocode/mpack#12] opened 2015-08-25 17:18 UTC
Hi Nicholas,

I was compiling Mpack for a non-Linux platform today (non-GNU) and ran into a big list of warnings (46 to be exact). Since we want to compile our code with `-Werror` we really want to fix it. But we need your opinion on this.

See some of our warnings below this. We are using the amalgamation package, so line-numbers are crazy, but you will get the point. The compiler moans about the check within `#if` while the variable is not defined.

In the example of the first warning:
```c
#if MPACK_STDLIB
```
should become:
```c
#if defined(MPACK_STDLIB) && MPACK_STDLIB
```

but this creates a mess in the code. From my point of view, you want to use:
```c
#ifdef MPACK_STDLIB
```
or
```c
#if defined(MPACK_STDLIB)
```

but this changes the behavior when configuring Mpack, only setting config to `0` wouldn't suffice. You need to disable the config option completely.

We are using GCC 4.9.3 Linaro arm-none-eabi cross-tools.

I can fix this and make a PR for you. But (since it is your lib) I need your input on this.

Thanks,

Rik

```
/3rdparty/mpack/src/mpack/mpack.h:78:5: warning: "MPACK_STDLIB" is not defined [-Wundef]
 #if MPACK_STDLIB
     ^
/3rdparty/mpack/src/mpack/mpack.h:82:5: warning: "MPACK_STDIO" is not defined [-Wundef]
 #if MPACK_STDIO
     ^
/3rdparty/mpack/src/mpack/mpack.h:85:5: warning: "MPACK_SETJMP" is not defined [-Wundef]
 #if MPACK_SETJMP
     ^
/3rdparty/mpack/src/mpack/mpack.h:113:7: warning: "_MSC_VER" is not defined [-Wundef]
 #elif _MSC_VER
       ^
/3rdparty/mpack/src/mpack/mpack.h:192:5: warning: "MPACK_STDLIB" is not defined [-Wundef]
 #if MPACK_STDLIB
     ^
/3rdparty/mpack/src/mpack/mpack.h:224:5: warning: "MPACK_READ_TRACKING" is not defined [-Wundef]
 #if MPACK_READ_TRACKING && (!defined(MPACK_READER) || !MPACK_READER)
     ^
/3rdparty/mpack/src/mpack/mpack.h:227:5: warning: "MPACK_WRITE_TRACKING" is not defined [-Wundef]
 #if MPACK_WRITE_TRACKING && (!defined(MPACK_WRITER) || !MPACK_WRITER)
     ^
/3rdparty/mpack/src/mpack/mpack.h:231:9: warning: "MPACK_STDIO" is not defined [-Wundef]
     #if MPACK_STDIO
         ^
/3rdparty/mpack/src/mpack/mpack.h:234:9: warning: "MPACK_READ_TRACKING" is not defined [-Wundef]
     #if MPACK_READ_TRACKING
         ^
/3rdparty/mpack/src/mpack/mpack.h:237:9: warning: "MPACK_WRITE_TRACKING" is not defined [-Wundef]
     #if MPACK_WRITE_TRACKING
         ^
/3rdparty/mpack/src/mpack/mpack.h:559:5: warning: "MPACK_READ_TRACKING" is not defined [-Wundef]
 #if MPACK_READ_TRACKING || MPACK_WRITE_TRACKING
     ^
/3rdparty/mpack/src/mpack/mpack.h:559:28: warning: "MPACK_WRITE_TRACKING" is not defined [-Wundef]
 #if MPACK_READ_TRACKING || MPACK_WRITE_TRACKING
                            ^
/3rdparty/mpack/src/mpack/mpack.h:780:5: warning: "MPACK_WRITE_TRACKING" is not defined [-Wundef]
 #if MPACK_WRITE_TRACKING
     ^
/3rdparty/mpack/src/mpack/mpack.h:827:9: warning: "MPACK_SETJMP" is not defined [-Wundef]
     #if MPACK_SETJMP
         ^
/3rdparty/mpack/src/mpack/mpack.h:833:9: warning: "MPACK_WRITE_TRACKING" is not defined [-Wundef]
     #if MPACK_WRITE_TRACKING
         ^
/3rdparty/mpack/src/mpack/mpack.h:882:5: warning: "MPACK_STDIO" is not defined [-Wundef]
 #if MPACK_STDIO
     ^
/3rdparty/mpack/src/mpack/mpack.h:906:5: warning: "MPACK_SETJMP" is not defined [-Wundef]
 #if MPACK_SETJMP
     ^
/3rdparty/mpack/src/mpack/mpack.h:1203:5: warning: "MPACK_WRITE_TRACKING" is not defined [-Wundef]
 #if MPACK_WRITE_TRACKING
     ^
/3rdparty/mpack/src/mpack/mpack.h:1298:5: warning: "MPACK_READ_TRACKING" is not defined [-Wundef]
 #if MPACK_READ_TRACKING
     ^
/3rdparty/mpack/src/mpack/mpack.h:1351:9: warning: "MPACK_SETJMP" is not defined [-Wundef]
     #if MPACK_SETJMP
```

**Comment by rikvdh** [comment] 2015-08-27 06:06
I found the option which enables the warnings. It is the `-Wundef`option.

Kind regards,

Rik

**Comment by ludocode** [comment] 2015-08-27 06:18
Ah, yeah. Do you still need this fixed? I had originally wanted to avoid needing to support this warning. I don't necessarily agree with the warning anyway; the behaviour of `#if` on an undefined preprocessor macro has been well-defined for a long time, and in the case of using a macro as a boolean flag, there isn't really a risk of unexpected behaviour from it not being defined. It's kind of a silly warning.  I also preferred using a plain `#if` because it allows macros to be defined as zero to disable a feature, and it catches attempts to change them without needing the verbose `#if defined(X) && X`. For example if it's defined `0` in one place, but then somewhere else defines it as `1` or vice-versa, you'll get a compiler error about redefining to something else. This isn't the case when using undefined versus defined blank as a boolean flag.

But, I've also seen `-Wundef` being commonly used especially on embedded platforms, and I've had to support it on other projects before. It sounds something like what you're working on, and is probably why it was defined on your project. So I suppose I should support it.

I agree that we can't just change to `#ifdef` since it would change behaviour if people were defining configuration options to `0`. But I'm somewhat torn on which direction to go. We could either add a check to `mpack-common.h` that requires that configuration options be defined to `1` or not defined at all; then we can just use `#ifdef`. Or we can use `#if defined(X) && X` everywhere. Or we can add some code to `mpack-common.h` which undefs any of the macros defined to `0`, then use `#ifdef` (probably the worst solution.) There are different pros and cons, and I haven't figured out which one to go with yet (or whether I should just leave it the way it is.)

In any case the boolean checks for `_MSC_VER` can be simply be changed to `defined(_MSC_VER)`. That one is a straightforward fix.

**Comment by rikvdh** [comment] 2015-08-28 04:47
I've added a PR for the _MSC_VER and also WIN32.

Is there a lot of legacy to support already? Perhaps is now the good time to make incompatible changes. I'd prefer `#ifdef` or `#if defined()`This keeps the code clean, prevents warnings on `-Wundef`. We could make a mpack-compat.h and leave it there which does:

```c
#if defined(VAR) && !VAR
#error You must remove VAR in order to unset it
#endif
```

And leave it there for a few versions. This would at least have my preference.

**Comment by ludocode** [comment] 2015-08-28 04:52
I was actually leaning the other direction, `#undef`ing any that are defined to something that doesn't evaluate to true. This doesn't break backwards compatibility, and continues to allow them to be defined to `0`. The `mpack-config.h.sample` should probably be written like this anyway:

```c
#ifndef MPACK_WRITER
#define MPACK_WRITER 1
#endif
```

That way you can use the default config file, but override some by pre-defining them to zero in your project configuration or whatever.

**Comment by ludocode** [comment] 2015-08-28 05:24
Fixed on branch develop in a3fd12fef21e157eac9a97f7c589f104d9d90b29. The unit tests now build with `-Wundef`. Give it a try. (You can generate a replacement amalgamated `mpack.{h,c}` by running `tools/package.sh`. I probably won't be doing a new release for a few weeks.)

**Comment by rikvdh** [comment] 2015-08-29 11:32
Looks fine to me. I've not tested it yet, but it seems correct. Perhaps it is a good idea to add `#warning` next to the `#undef`'s to let people know that the way that configuration works changed instead of silently supporting both. In the future you probably only want to support one method.

https://github.com/ludocode/mpack/blob/a3fd12fef21e157eac9a97f7c589f104d9d90b29/src/mpack/mpack-platform.h#L51-L86

:)

**Comment by ludocode** [comment] 2015-09-14 06:10
I'm actually thinking of switching over to a fourth option, which is that instead of undefining any options that are 0 in `mpack-platform.h`, it should instead define any undefined ones to 0. This way we can go back to using `#if` instead of `#ifdef` everywhere.

This is probably the least error-prone option (or at least it would have been before we switched over to `#ifdef`, since switching back might be messy.) We avoid `#ifdef` as much as possible, and if we forget to add a new configuration option to `mpack-platform.h` or use one before they get defined to 0, we get a nice warning due to `-Wundef`. This is in contrast to the current situation where if we forget to undefine a new configuration option in `mpack-platform.h` or `#ifdef` one before `mpack-platform.h`, we just get the wrong result.

**Comment by ludocode** [comment] 2015-09-19 15:40
Switched over to defining to 0 any undefined options. This way we support `-Wundef`, we use `#if` for all configuration switches, and if we forget an option, we get compiler errors instead of silent failures.

https://github.com/ludocode/mpack/blob/8494718102899f4e54a0509665d97ac24a191378/src/mpack/mpack-platform.h#L48-L105

This is also much closer to the original code, since 8494718102899f4e54a0509665d97ac24a191378 reverts much of a3fd12fef21e157eac9a97f7c589f104d9d90b29. There are no behavioural changes between versions of MPack, so there shouldn't be any necessity for `#warning`s to be added. Hopefully we've converged on the best solution!

**Closed** 2015-09-27 16:04 UTC
